<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ModuleCatalog extends \AppBundle\Entity\ModuleCatalog implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'parentId', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'urlAccess', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'orderModule', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'visible', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'moduleIcon', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'createdBy', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'updatedBy');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'parentId', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'urlAccess', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'orderModule', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'visible', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'moduleIcon', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'createdBy', '' . "\0" . 'AppBundle\\Entity\\ModuleCatalog' . "\0" . 'updatedBy');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ModuleCatalog $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentId($parentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentId', array($parentId));

        return parent::setParentId($parentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentId', array());

        return parent::getParentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlAccess($urlAccess)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlAccess', array($urlAccess));

        return parent::setUrlAccess($urlAccess);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlAccess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlAccess', array());

        return parent::getUrlAccess();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderModule($orderModule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderModule', array($orderModule));

        return parent::setOrderModule($orderModule);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderModule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderModule', array());

        return parent::getOrderModule();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible($visible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', array($visible));

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', array());

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setModuleIcon($moduleIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModuleIcon', array($moduleIcon));

        return parent::setModuleIcon($moduleIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleIcon', array());

        return parent::getModuleIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(\AppBundle\Entity\User $createdBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($createdBy));

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy(\AppBundle\Entity\User $updatedBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', array($updatedBy));

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', array());

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
