AppBundle\Entity\Organization:
    type: entity
    table: organization
    repositoryClass: AppBundle\Repository\OrganizationRepository
    indexes:
        organization2user_idx:
            columns:
                - created_by
        organization2user2_idx:
            columns:
                - updated_by
    id:
        organizationId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: organization_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 300
            fixed: false
        address:
            type: string
            nullable: true
            length: 2000
            fixed: false            
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
        status:
            type: string
            nullable: true
            length: null
            fixed: false
            default: ACTIVO
        passwdApp:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: passwd_app
    lifecycleCallbacks: {  }
