AppBundle\Entity\Status:
    type: entity
    table: status
    id:
        statusId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: status_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            fixed: false
        isActive:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: is_active
    lifecycleCallbacks: {  }
