AppBundle\Entity\UserPolygon:
    type: entity
    table: user_polygon
    id:
        userPolygonId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: user_polygon_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            fixed: false
        type:
            type: string
            nullable: true
            length: 45
            fixed: false
        userId:
            type: integer
            nullable: true
            unsigned: false
            column: user_id
        coordinates:
            type: string
            nullable: true
            length: 1000
            fixed: false
        status:
            type: integer
            nullable: true
            unsigned: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
        polygonCid:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: polygon_cid
    lifecycleCallbacks: {  }
