AppBundle\Entity\UserSchedule:
    type: entity
    table: user_schedule
    indexes:
        fk_user_id_1002_idx:
            columns:
                - user_id
        fk_origanization_id_10023_idx:
            columns:
                - organization_id
        fk_category_id_2001_idx:
            columns:
                - category_id
        fk_event_id_5201_idx:
            columns:
                - event_id
        fk_created_by_5201_idx:
            columns:
                - created_by
    id:
        userScheduleId:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: user_schedule_id
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: true
            unsigned: false
            column: user_id
        organizationId:
            type: integer
            nullable: true
            unsigned: false
            column: organization_id
        weekday:
            type: string
            nullable: true
            length: 45
            fixed: false
        startAt:
            type: datetime
            nullable: true
            column: start_at
        endAt:
            type: datetime
            nullable: true
            column: end_at
        isActive:
            type: integer
            nullable: true
            unsigned: false
            column: is_active
        categoryId:
            type: integer
            nullable: true
            unsigned: false
            column: category_id
        eventId:
            type: integer
            nullable: true
            unsigned: false
            column: event_id
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
    lifecycleCallbacks: {  }
