AppBundle\Entity\UserRole:
    type: entity
    table: user_role
    indexes:
        fk_created_by_1011_idx:
            columns:
                - created_by
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 64
            fixed: false
        description:
            type: string
            nullable: true
            length: 512
            fixed: false
        active:
            type: boolean
            nullable: false
            default: '1'
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    lifecycleCallbacks: {  }
