AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: AppBundle\Repository\UserRepository
    indexes:
        fk_user_role_id_100_idx:
            columns:
                - user_role_id
        fk_created_by_1008_idx:
            columns:
                - created_by
        fk_organization_id_1005_idx:
            columns:
                - organization_id
        fk_user_role_id_1001_idx:
            columns:
                - user_role_id
        fk_organization_id_1008_idx:
            columns:
                - organization_id
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: last_name
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
        password:
            type: string
            nullable: false
            length: 72
            fixed: false
        status:
            type: string
            nullable: false
            length: null
            fixed: false
            default: ACTIVO
        userRoleId:
            type: integer
            nullable: true
            unsigned: false
            column: user_role_id
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        bio:
            type: text
            nullable: true
            length: 65535
            fixed: false
        avatarPath:
            type: string
            nullable: true
            length: 300
            fixed: false
            column: avatar_path
        gainFactor:
            type: decimal
            nullable: true
            precision: 3
            scale: 2
            column: gain_factor
        securityCode:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: security_code
        userOrder:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: user_order
        legal:
            type: integer
            nullable: true
            unsigned: false
    manyToOne:
        organization:
            targetEntity: Organization
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                organization_id:
                    referencedColumnName: organization_id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
        userRole:
            targetEntity: UserRole
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_role_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
