AppBundle\Entity\UserRoleModulePermission:
    type: entity
    table: user_role_module_permission
    indexes:
        fk_user_role_id_1002_idx:
            columns:
                - user_role_id
        fk_module_id_1001_idx:
            columns:
                - module_id
        fk_created_by_1012_idx:
            columns:
                - created_by
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userRoleId:
            type: integer
            nullable: true
            unsigned: false
            column: user_role_id
        moduleId:
            type: integer
            nullable: true
            unsigned: false
            column: module_id
        viewModule:
            type: boolean
            nullable: false
            default: '0'
            column: view_module
        readPermission:
            type: boolean
            nullable: false
            default: '0'
            column: read_permission
        writePermission:
            type: boolean
            nullable: false
            default: '0'
            column: write_permission
        editPermission:
            type: boolean
            nullable: false
            default: '0'
            column: edit_permission
        deletePermission:
            type: boolean
            nullable: false
            default: '0'
            column: delete_permission
        mainModule:
            type: boolean
            nullable: false
            default: '0'
            column: main_module
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            column: created_by
        updatedBy:
            type: integer
            nullable: true
            unsigned: false
            column: updated_by
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    lifecycleCallbacks: {  }
